vidly/movies/urls.py
from django.urls import path
from . import views


app_name = 'movies'
urlpatterns = [
    path('',views.index , name = "index"),
    path('<int:movie_id>', views.detail , name = "detail")
]

vidly/vidly/urls.py
from django.contrib import admin
from django.urls import path,include
from api.models import MovieResource
from . import views


movie_resource = MovieResource()



urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('api/',include(movie_resource.urls))
]

vidly/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['Date_created','release_date'] 
        
        
    

vidly/movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length= 255)
    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length= 255)
    release_year = models.IntegerField()
    number_in_stuck = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre , on_delete= models.CASCADE)
    Date_created = models.DateField(default= timezone.now)
    
    def __str__(self):
        return self.title

vidly/api/views.py
from django.shortcuts import render

# Create your views here.

vidly/movies/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Movie
# Create your views here.

def index(request):
    movies = Movie.objects.all()
    return render(request , "movies/index.html", {'movies': movies})

def detail(request, movie_id):
    
     movie = get_object_or_404(Movie, id=movie_id) 
     return render(request, "movies/detail.html", {'movie': movie})
    

vidly/vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

vidly/movies/templates/movies/detail.html
{% extends "base.html" %}
{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{ movie.title }}</dd>
        <dt>Genre</dt>
        <dd>{{ movie.genre }}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stuck}}</dd>
        <dt>Daily rate</dt>
        <dd>{{movie.daily_rate}}</dd>
    </dl>
{% endblock  %}

vidly/movies/templates/movies/index.html
{% extends "base.html" %}

{% block content %}
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Daily Rate</th>
            </tr>
        </thead>
        <tbody>
            {% for movie  in movies  %}
            <tr>
                <td>
                    <a href="{% url "movies:detail" movie.id %}">
                        {{ movie.title }}
                    </a>
                </td>
                <td> {{ movie.genre}} </td>
                <td> {{ movie.number_in_stuck}}</td>
                <td> {{ movie.daily_rate }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
{% endblock  %}

vidly/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Vidly</a>
      </div>
    </nav>
    <main class="container">
      {%block content %}
      {%endblock%}
    </main>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  </body>
</html>

vidly/templates/home.html
{% extends "base.html" %}


{% block content  %}
    <a href="{% url "movies:index" %}">Movies</a>
{% endblock %}